---
- name: Bootstrap AWS credentials
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
    kubeconfig: "{{ kubeconfig.path }}"
  with_items:
    - aws-credentials-ns.yaml.j2
    - awssm-secret.yaml.j2
  when:
    - aws_secret_access_key is defined and aws_secret_access_key != ""
    - aws_access_key_id is defined and aws_access_key_id != ""

- name: Bootstrap Bitwarden credentials
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
    kubeconfig: "{{ kubeconfig.path }}"
  with_items:
    - bitwarden-ns.yaml.j2
    - bitwarden-secret.yaml.j2
  when:
    - bitwarden_user is defined and bitwarden_user != ""
    - bitwarden_password is defined and bitwarden_password != ""
    - bitwarden_host is defined and bitwarden_host != ""
